apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.web_image.config_ref }}
data:
  # property-like keys; each key maps to a simple value
  AWS_DYNAMO-DB_TABLE-NAME: {{ .Values.dynamodb_table_name }}
  AWS_SNS_TOPIC-NAME: {{ .Values.sns_topic_arn }}
  S3_BUCKET-NAME: {{ .Values.s3_bucket }}
  AWS_SNS_FROM: {{ .Values.sns_from }}