apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db_image.serect_ref }}
type: Opaque
data:
  FLYWAY_USER: {{ .Values.db_user }}
  FLYWAY_PASSWORD: {{ .Values.db_password }}
  FLYWAY_URL: {{ .Values.jdbc_url }}