# echo -n 'csye7125' | base64  
# echo -n 'jdbc:mysql://csye7125.cmibil0ifabu.us-east-1.rds.amazonaws.com:3306/todo' | base64  
# echo -n '12345678' | base64  

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.web_image.serect_ref }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.db_user }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.db_password }}
  SPRING_DATASOURCE_URL: {{ .Values.jdbc_url }}
  AWS_ACCESS_KEY_ID: {{ .Values.ses_access_key }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ses_secret_key }}